### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by hannojg** [barinbritva/init-typescript-app#11]
```
command: npm run build:dev

> ts-node --project ./tsconfig-dev.json ./tasks/run-build.ts -d

/Users/hannogodecke/Cuvent/app/redux-state-debugger/tasks/build.ts:14
    if (typeof config === 'object' && config?.compilerOptions?.outDir != null) {
                                             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Module.m._compile (/Users/hannogodecke/Cuvent/app/redux-state-debugger/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/hannogodecke/Cuvent/app/redux-state-debugger/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/hannogodecke/Cuvent/app/redux-state-debugger/tasks/run-build.ts:1:1)
```

**Comment by hannojg** [comment]
same for dev and not dev

**Comment by hannojg** [comment]
my tsconfig:

```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "resolveJsonModule": true,
    "jsx": "react",
    "lib": [
      "esnext",
      "dom"
    ],
    "moduleResolution": "node",
    "target": "esnext",
    "baseUrl": "./",
    "strict": true,
    "skipLibCheck": true,
    "outDir": "./dist",
    "paths": {
      "@utilities/*": ["lib/common/utilities/*"],
      "@styles/*": ["lib/common/styles/*"],
      "@common/*": ["lib/common/*"],
      "lib/*": ["lib/*"],
    }
  },
  "include": [
    "./src",
    "./lib"
  ],
  "exclude": [
    ".*__test.*"
  ],
}
```

(changed it)

**Comment by hannojg** [comment]
ah okay, my tsconfig.json wasn't valid json - fixed that

**Comment by barinbritva** [comment]
Hi @hannojg,

Build script parses `tsconfig.json`  using JSON.parse to get `outDir` value. That's why some things like trailing commas and comments which are totally OK for tsconfig, emit errors in build script. It's not convenient and I will fix it in next release.

Sorry for that. And thanks for reaching me out.
